/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techquizapp.Gui;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import edu.cmu.sphinx.api.Configuration;
import edu.cmu.sphinx.api.LiveSpeechRecognizer;
import edu.cmu.sphinx.api.SpeechResult;
import speechrecog.LoginSR;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import techquizapp.Dao.UserDao;
import techquizapp.Pojo.UserPojo;
import techquizapp.Pojo.UserProfile;

/**
 *
 * @author DeepakChaurasia
 */
public class LoginFrame extends javax.swing.JFrame {

    private String username;
    private String password;
    //  private LoginSR s;
    private TextToVoice tv;
    private VoiceToText vt;

    public LoginFrame() {
        // s = new LoginSR();
        this.setUndecorated(true);
        initComponents();
        tv = new TextToVoice();
        tv.start();
        vt = new VoiceToText();
        vt.start();
        // this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jrStudent = new javax.swing.JRadioButton();
        jrAdmin = new javax.swing.JRadioButton();
        btnQuit = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("User Login Screen");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("UserName");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(576, 4));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Login To Your Account");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 70, 580, 120);

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jPanel1.add(txtPassword);
        txtPassword.setBounds(650, 452, 280, 40);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2), "User Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 28), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jrStudent.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrStudent);
        jrStudent.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jrStudent.setForeground(new java.awt.Color(153, 0, 153));
        jrStudent.setText(" Student");

        jrAdmin.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrAdmin);
        jrAdmin.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jrAdmin.setForeground(new java.awt.Color(153, 0, 153));
        jrAdmin.setText(" Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(jrAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(jrStudent)
                .addGap(207, 207, 207))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 780, 930, 150);

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(153, 0, 153));
        btnQuit.setText("Quit");
        btnQuit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit);
        btnQuit.setBounds(630, 590, 190, 40);

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(153, 0, 153));
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(260, 590, 190, 40);

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel1.add(txtUsername);
        txtUsername.setBounds(650, 340, 280, 43);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 440, 340, 70);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Username");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 330, 340, 70);

        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/4aa5221304f1eee21660bb417195daac.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 3150, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        tv.changeState();
        boolean isValidInput = validateInputs();
        if (isValidInput == false) {
            JOptionPane.showMessageDialog(null, "Username or Password cannot be left blank!", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String userType = getUserType();
        if (userType == null) {
            JOptionPane.showMessageDialog(null, "Please choose user type", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            UserPojo user = new UserPojo();
            user.setUserid(username);
            user.setPassword(password);
            user.setUserType(userType);
            boolean isValidUser = UserDao.validateUser(user);

            if (isValidUser) {
                //  JOptionPane.showMessageDialog(null,"Login Accepted!", "Welcome"+username, JOptionPane.INFORMATION_MESSAGE);

                //vt.stlstn();
               
              /*  try {
                    Thread.sleep(10000);
                    
                } catch (InterruptedException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }*/
                System.out.println("clicked");
                UserProfile.setUsername(username);
                UserProfile.setUsertype(userType);
                if (user.getUserType().equalsIgnoreCase("admin")) {
                    AdminOptionsFrame adminFrame = new AdminOptionsFrame();    //to be created
                    adminFrame.setVisible(true);
                } else {
                    StudentOptionsFrame studentFrame = new StudentOptionsFrame();
                    studentFrame.setVisible(true);
                }
                this.dispose();
                 vt.stop();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid username or password or usertype!", "Not Authorized!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error while connecting to DB!", "Error!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnQuit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jrAdmin;
    private javax.swing.JRadioButton jrStudent;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private boolean validateInputs() {
        username = txtUsername.getText();
        char[] pwd = txtPassword.getPassword();

        if (username.isEmpty() || pwd.length == 0) {
            return false;
        } else {
            password = String.valueOf(pwd);
            return true;
        }
    }

    private String getUserType() {
        if (jrAdmin.isSelected()) {
            return "admin";
        } else if (jrStudent.isSelected()) {
            return "student";
        } else {
            return null;
        }
    }

    class TextToVoice extends Thread {

        public static final String VOICENAME = "kevin16";
        private Voice voice;

        public void run() {
            try {
                Thread.sleep(700);
                VoiceManager vm = VoiceManager.getInstance();
                voice = vm.getVoice(VOICENAME);
                voice.allocate();
                voice.speak("Hello,    Log in to your account    !!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        public void changeState() {
            voice.deallocate();
        }
    }

    class VoiceToText extends Thread {

        private boolean flag = true;

        public void run() {
            try {
                Thread.sleep(1000);
                //LoginSR s = new LoginSR();
                /*   LiveSpeechRecognizer recognizer = s.lsr();
                recognizer.startRecognition(true);
                SpeechResult result = recognizer.getResult();
                
                
                while ((result = recognizer.getResult()) != null && flag) {
                    String speech = result.getHypothesis();
                    System.out.println("speech: "+speech);
                    System.out.println(flag);
                    if (speech.equalsIgnoreCase("admin")) {
                        jrAdmin.setSelected(true);
                    } else if (speech.equalsIgnoreCase("student")) {
                        jrStudent.setSelected(true);
                    } else if (speech.equalsIgnoreCase("Login")) {
                        btnLogin.doClick();
                    } else if (speech.equalsIgnoreCase("quit")) {
                        btnQuit.setSelected(true);
                    } else if (speech.equalsIgnoreCase("<unk>"));
                    else{
                    }
                }*/

                while (flag) {
                    String speech = LoginSR.speech();
                    System.out.println("speech: Login " + speech);
                    System.out.println(flag);
                    if (speech.equalsIgnoreCase("admin")) {
                        jrAdmin.setSelected(true);
                    } else if (speech.equalsIgnoreCase("student")) {
                        jrStudent.setSelected(true);
                    } else if (speech.equalsIgnoreCase("Login")) {
                        btnLogin.doClick();
                    } else if (speech.equalsIgnoreCase("quit")) {
                        btnQuit.setSelected(true);
                    } else if (speech.equalsIgnoreCase("<unk>")); else {
                    }
                }
                //recognizer.stopRecognition();
                System.out.println("dddddddddddddddddddddddddddddddddd");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        public void stlstn() {
          /*  Thread.interrupted();
            dispose();*/
            flag = false;
        }
    }
}
